# coding: utf-8

# Copyright Luna Technology 2015
# Matthieu Riviere <mriviere@luna-technology.com>

from luna_django_commons.app.helpers import choices_from_mapping


DATAFILE_UPLOAD_IN_PROGRESS = 'DATAFILE_UPLOAD_IN_PROGRESS'
DATAFILE_TRANSFER_IN_PROGRESS = 'DATAFILE_TRANSFER_IN_PROGRESS'
DATAFILE_ERROR = 'DATAFILE_ERROR'
DATAFILE_READY = 'DATAFILE_READY'

DATAFILE_STATES = {
    DATAFILE_UPLOAD_IN_PROGRESS: 'Upload in progress',
    DATAFILE_TRANSFER_IN_PROGRESS: 'Transfer in progress',
    DATAFILE_ERROR: 'Error',
    DATAFILE_READY: 'Ok',
}

DATAFILE_STATE_CHOICES = choices_from_mapping(DATAFILE_STATES)


STORAGE_ACCOUNT_PENDING_VALIDATION = 'STORAGE_ACCOUNT_PENDING_VALIDATION'
STORAGE_ACCOUNT_VALIDATING = 'STORAGE_ACCOUNT_VALIDATING'
STORAGE_ACCOUNT_READY = 'STORAGE_ACCOUNT_READY'
STORAGE_ACCOUNT_VALIDATION_FAILED = 'STORAGE_ACCOUNT_VALIDATION_FAILED'

STORAGE_ACCOUNT_STATES = {
    STORAGE_ACCOUNT_PENDING_VALIDATION: 'Pending validation',
    STORAGE_ACCOUNT_VALIDATING: 'Validation in progress',
    STORAGE_ACCOUNT_READY: 'Ready',
    STORAGE_ACCOUNT_VALIDATION_FAILED: 'Validation failed',
}
STORAGE_ACCOUNT_STATE_CHOICES = choices_from_mapping(STORAGE_ACCOUNT_STATES)


ACTION_TYPE_UPLOAD = 'ACTION_TYPE_UPLOAD'
ACTION_TYPE_DOWNLOAD = 'ACTION_TYPE_DOWNLOAD'
ACTION_TYPE_CREATE_FOLDER = 'ACTION_TYPE_CREATE_FOLDER'
ACTION_TYPE_DELETE_FILE = 'ACTION_TYPE_DELETE_FILE'
ACTION_TYPE_CREATE_DATASET = 'ACTION_TYPE_CREATE_DATASET'
ACTION_TYPE_DELETE_DATASET = 'ACTION_TYPE_DELETE_DATASET'
ACTION_TYPE_PUBLISH_DATASET = 'ACTION_TYPE_PUBLISH_DATASET'
ACTION_TYPE_UNPUBLISH_DATASET = 'ACTION_TYPE_UNPUBLISH_DATASET'
ACTION_TYPE_DOWNLOAD_DATASET = 'ACTION_TYPE_DOWNLOAD_DATASET'
ACTION_TYPE_JOBPORTAL_SUBMIT = 'ACTION_TYPE_JOBPORTAL_SUBMIT'

ACTION_TYPE_UPLOAD_TEXT = '%(user)s uploaded file: %(path)s'
ACTION_TYPE_DOWNLOAD_TEXT = '%(user)s downloaded file: %(path)s'
ACTION_TYPE_CREATE_FOLDER_TEXT = '%(user)s created folder: %(path)s'
ACTION_TYPE_DELETE_FILE_TEXT = '%(user)s deleted file: %(path)s'
ACTION_TYPE_CREATE_DATASET_TEXT = '%(user)s created dataset: %(dataset)s'
ACTION_TYPE_DELETE_DATASET_TEXT = '%(user)s deleted dataset: %(dataset)s'
ACTION_TYPE_PUBLISH_DATASET_TEXT = '%(user)s published dataset: %(dataset)s'
ACTION_TYPE_UNPUBLISH_DATASET_TEXT = '%(user)s unpublished dataset: %(dataset)s'
ACTION_TYPE_DOWNLOAD_DATASET_TEXT = 'An anonymous user downloaded dataset: %(dataset)s'
ACTION_TYPE_JOBPORTAL_SUBMIT_TEXT = '%(user)s submitted a job on portal: %(portal)s'

ACTIONS_TEXT = {
    ACTION_TYPE_UPLOAD: ACTION_TYPE_UPLOAD_TEXT,
    ACTION_TYPE_DOWNLOAD: ACTION_TYPE_DOWNLOAD_TEXT,
    ACTION_TYPE_CREATE_FOLDER: ACTION_TYPE_CREATE_FOLDER_TEXT,
    ACTION_TYPE_DELETE_FILE: ACTION_TYPE_DELETE_FILE_TEXT,
    ACTION_TYPE_CREATE_DATASET: ACTION_TYPE_CREATE_DATASET_TEXT,
    ACTION_TYPE_DELETE_DATASET: ACTION_TYPE_DELETE_DATASET_TEXT,
    ACTION_TYPE_PUBLISH_DATASET: ACTION_TYPE_PUBLISH_DATASET_TEXT,
    ACTION_TYPE_UNPUBLISH_DATASET: ACTION_TYPE_UNPUBLISH_DATASET_TEXT,
    ACTION_TYPE_DOWNLOAD_DATASET: ACTION_TYPE_DOWNLOAD_DATASET_TEXT,
    ACTION_TYPE_JOBPORTAL_SUBMIT: ACTION_TYPE_JOBPORTAL_SUBMIT_TEXT,
}


EXTERNAL_SUBMISSION_PENDING_SUBMISSION = 'EXTERNAL_SUBMISSION_PENDING_SUBMISSION'
EXTERNAL_SUBMISSION_PENDING = 'EXTERNAL_SUBMISSION_PENDING'
EXTERNAL_SUBMISSION_RUNNING = 'EXTERNAL_SUBMISSION_RUNNING'
EXTERNAL_SUBMISSION_SUCCESS = 'EXTERNAL_SUBMISSION_SUCCESS'
EXTERNAL_SUBMISSION_FAILED = 'EXTERNAL_SUBMISSION_FAILED'

EXTERNAL_SUBMISSION_STATES = {
    EXTERNAL_SUBMISSION_PENDING_SUBMISSION: 'Submission in progress',
    EXTERNAL_SUBMISSION_PENDING: 'Pending',
    EXTERNAL_SUBMISSION_RUNNING: 'Running',
    EXTERNAL_SUBMISSION_SUCCESS: 'Succeeded',
    EXTERNAL_SUBMISSION_FAILED: 'FAILED'
}
EXTERNAL_SUBMISSION_STATE_CHOICES = choices_from_mapping(EXTERNAL_SUBMISSION_STATES)
